name: "web_app"
mode: "dev"
port: 8081
version: "0.1.0"

log:
  filename: "web_app.log"
  level: "debug"
  max_size: 200
  max_age: 300
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "12345678"
  dbname: "sql_demo"
  max_open_conns: 10
  max_idle_conns: 5


redis:
  host: "127.0.0.1"
  port: 6379
  db: 1
  password: ""
  pool_size: 100